### ISSUE TITLE
Can't get plugin to work.

### ISSUE THREAD

**Issue by ultrathew** [SynTexDZN/homebridge-syntex-webhooks#1]
Attempting to use to create a single switch. Keep getting this error on Homebridge restart:

[SynTexWebHooks] [ERROR] Es wurden keine Hintergrundprozesse geladen!

And this error every time I try to send an HTTP request to a formatted URL:

[SynTexWebHooks] [ERROR] Es wurde kein passendes Gerät in der Config gefunden! ( sensor1 )

Config is:
        {
            "platform": "SynTexWebHooks",
            "port": 1710,
            "cache_directory": "./SynTex/",
            "log_directory": "./SynTex/log",
            "devices": [
                {
                    "mac": "sensor1",
                    "name": "Plants",
                    "service": "switch"
                }
            ]
        }

**Comment by SynTexDZN** [comment]
Oh, that's my fault! I updated the plugin while not updating the README. I't is only a small mistake. Simply replace "devices" with "accessories" and it should work properly. :)

The first error you get can't be ignored if you don't wan't to use automation which are currently under development. I also work on a multilingual version of the log output to make you understand errors without using Google Translator ;D

I will update the README later on thanks for your report.

**Comment by ultrathew** [comment]
Thank you! All is working as expected now.

**Comment by SynTexDZN** [comment]
You're welcome. If you have any ideas for new features, problems or unexpected behavior you can simply open a new request :) I hope you'll enjoy the plugin.
