### ISSUE TITLE
MagicHome Collaboration

### ISSUE THREAD

**Issue by Zacknetic** [SynTexDZN/homebridge-syntex-webhooks#3]
Hello,

I'm a MagicHome plugin dev too! Would you be interested in opening a dialogue? Perhaps we can compare notes. I'm sure there's a lot I can learn from you.

Let me know that sounds like something you'd like to do.

Thank you.

**Comment by SynTexDZN** [comment]
Sure,
I started to learn node plugin development some months before.
If you want to open a dialogue you can contact me on Discord. My username is: SynTex#7536
