### ISSUE TITLE
More examples of dimmer configuration

### ISSUE THREAD

**Issue by Hari-Seldon-nl** [SynTexDZN/homebridge-syntex-webhooks#6]
**Is your feature request related to a problem? Please describe.**
Documentation unclear, and therefore usability not optimal 

**Describe the solution you'd like**
Provide some more examples for 'dimmer' and how the value of accessory can be translated in a value in the URL. Current documentation provides not enough explanation how it works.

**Describe alternatives you've considered**
none

**Additional context**
I really like the Syntex Webhook and I'm using this for my old Home automation system which is also capable to control a dimmer via a http request.

**Comment by SynTexDZN** [comment]
I added some content for dimmable lights to the example config and README. If there is something that isn't clear or you don't understand please let me know :)

~ **SynTex**
