### ISSUE TITLE
Suddenly getting "Error: connect ETIMEDOUT 94.31.106.127:8888" over and over

### ISSUE THREAD

**Issue by ultrathew** [SynTexDZN/homebridge-syntex-webhooks#8]
**Describe the bug**
Constant errors in my HomeBridge logs that read:
[SynTexWebHooks] [ERROR] Error: connect ETIMEDOUT 94.31.106.127:8888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)

**Expected behavior**
No errors

**Config**
{
    "platform": "SynTexWebHooks",
    "baseDirectory": "/var/lib/homebridge/SynTex",
    "options": {
        "port": 1710,
        "language": "us"
    },
    "log": {
        "debug": false
    },
    "accessories": [
        {
            "id": "templeRH",
            "name": "Outdoor Humidity",
            "services": "humidity"
        },
        {
            "id": "templeTemp",
            "name": "Outdoor Temperature",
            "services": "temperature"
        }
    ]
}

**Logs**
[SynTexWebHooks] [ERROR] Error: connect ETIMEDOUT 94.31.106.127:8888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)

...over and over again, every few minutes

**More Information**
 - OS: Raspbian GNU/Linux Bullseye (11)
 - Node Version 18.12.1

**Comment by ultrathew** [comment]
Bumping this, as the problem seems to have reappeared. Any clues for how to resolve? My Homebridge log is filled with:

[SynTexWebHooks] [ERROR] Error: connect EHOSTUNREACH 94.31.106.127:8800
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

**Comment by SynTexDZN** [comment]
Hey @ultrathew,
The error message itself should be gone after installing the newest beta of the plugin I published today. A complete fix will come out the next days / weeks.

~ **SynTex**
